## **Carregamento da base de dados**

In [64]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np

In [65]:
path_despesas = "../data/despesas.csv"
path_deputados = "../data/deputados.csv"

In [44]:
df_deputados = pd.read_csv(path_deputados)
df_despesas = pd.read_csv(path_despesas)

In [45]:
df_deputados.head()

,id,uri,nomeParlamentar,siglaPartido,uriPartido,siglaUf,idLegislatura,urlFoto,email,sexo,ultimaSituacao,condicaoEleitoral,nomeEleitoral,nomeCivil,dataNascimento,falecido,udNascimento,escolaridade
0,1500,https://dadosabertos.camara.leg.br/api/v2/depu...,MÁRIO LIMA,"['PMDB', 'PSB*']",https://dadosabertos.camara.leg.br/api/v2/part...,['BA'],"[48, 42, 47]",https://www.camara.leg.br/internet/deputado/ba...,NaN,M,Vacância,Titular,MÁRIO LIMA,MÁRIO SOARES LIMA,1935-02-19,0,BA,Secundário
1,1501,https://dadosabertos.camara.leg.br/api/v2/depu...,MAURÍCIO FRUET,"['PMDB', 'MDB*']",https://dadosabertos.camara.leg.br/api/v2/part...,['PR'],"[48, 46, 47]",https://www.camara.leg.br/internet/deputado/ba...,NaN,M,Vacância,Titular,MAURÍCIO FRUET,Maurício Roslindo Fruet,1939-08-12,0,PR,Superior
2,1502,https://dadosabertos.camara.leg.br/api/v2/depu...,OSWALDO ALMEIDA,['PL*'],https://dadosabertos.camara.leg.br/api/v2/part...,['RJ'],[48],https://www.camara.leg.br/internet/deputado/ba...,NaN,M,NaN,Titular,OSWALDO ALMEIDA,Oswaldo Barreto de Almeida,1933-10-22,0,RJ,Superior
3,1503,https://dadosabertos.camara.leg.br/api/v2/depu...,OSWALDO LIMA FILHO,"['PMDB', 'PSP', 'MDB*', 'PTB']",https://dadosabertos.camara.leg.br/api/v2/part...,['PE'],"[40, 41, 42, 43, 47, 48]",https://www.camara.leg.br/internet/deputado/ba...,NaN,M,Vacância,Efetivado,OSWALDO LIMA FILHO,Oswaldo Cavalcanti da Costa Lima Filho,1921-04-26,0,PE,Superior
4,1504,https://dadosabertos.camara.leg.br/api/v2/depu...,TITO COSTA,['PMDB'],https://dadosabertos.camara.leg.br/api/v2/part...,['SP'],[48],https://www.camara.leg.br/internet/deputado/ba...,NaN,M,NaN,Suplente,TITO COSTA,Antonio Tito Costa,1922-12-31,0,SP,Superior

In [46]:
df_deputados.ultimaSituacao.value_counts()

ultimaSituacao
Vacância          1791
Fim de Mandato     989
Exercício          526
Suplência          289
Afastado           189
Licença             43
Convocado            4
Suspenso             1
Name: count, dtype: int64

In [47]:
df_despesas.head()

,ano,mes,tipoDespesa,codDocumento,tipoDocumento,codTipoDocumento,dataDocumento,numDocumento,valorDocumento,urlDocumento,nomeFornecedor,cnpjCpfFornecedor,valorLiquido,valorGlosa,numRessarcimento,codLote,parcela,id_deputado
0,2023,9,MANUTENÇÃO DE ESCRITÓRIO DE APOIO À ATIVIDADE ...,7610066,Nota Fiscal Eletrônica,4,2023-09-19T00:00:00,35537,52.98,http://www.camara.leg.br/cota-parlamentar/nota...,3XIS COMERCIO VAREJISTA E ATACADISTA DE PAPELA...,4.299980e+13,52.98,0.0,NaN,1969221,0,220593
1,2023,11,MANUTENÇÃO DE ESCRITÓRIO DE APOIO À ATIVIDADE ...,7657491,Nota Fiscal,0,2023-11-27T00:00:00,01,67.30,https://www.camara.leg.br/cota-parlamentar/doc...,AGUAS CUIABA S.A,1.499558e+13,67.30,0.0,NaN,1996163,0,220593
2,2023,5,MANUTENÇÃO DE ESCRITÓRIO DE APOIO À ATIVIDADE ...,7552621,Nota Fiscal,0,2023-05-05T00:00:00,11533052023001,43.20,https://www.camara.leg.br/cota-parlamentar/doc...,AGUAS CUIABA S.A,1.499558e+13,43.20,0.0,NaN,1938600,0,220593
3,2023,6,MANUTENÇÃO DE ESCRITÓRIO DE APOIO À ATIVIDADE ...,7587236,Recibos/Outros,1,2023-06-05T00:00:00,11533062023001,43.20,https://www.camara.leg.br/cota-parlamentar/doc...,AGUAS CUIABA S.A,1.499558e+13,43.20,0.0,NaN,1957493,0,220593
4,2023,7,MANUTENÇÃO DE ESCRITÓRIO DE APOIO À ATIVIDADE ...,7587239,Nota Fiscal,0,2023-07-05T00:00:00,11533072023001,43.20,https://www.camara.leg.br/cota-parlamentar/doc...,AGUAS CUIABA S.A,1.499558e+13,43.20,0.0,NaN,1957494,0,220593

In [48]:
df_despesas.numRessarcimento.sort_values(ascending=False).head(10)

523    0.0
524    0.0
525    0.0
526    0.0
527    0.0
528    0.0
529    0.0
530    0.0
531    0.0
532    0.0
Name: numRessarcimento, dtype: float64

In [49]:
df_despesas["parcela"].value_counts().head(10)

parcela
0    656813
1       349
Name: count, dtype: int64

In [50]:
df_despesas.valorGlosa.value_counts().head(10)

valorGlosa
0.00     627515
3.00        500
2.99        443
4.00        362
5.00        326
20.00       186
10.00       180
2.00        173
4.50        163
2.50        147
Name: count, dtype: int64

In [51]:
df_despesas.nomeFornecedor.value_counts()

nomeFornecedor
TAM                                      95869
UBER DO BRASIL TECNOLOGIA LTDA.          32083
GOL                                      29321
AZUL                                     26112
LATAM Airlines Brasil                     7749
                                         ...
POA APARICIO BORGES                          1
SAMUARA HOTEL                                1
real expresso                                1
ABAST DE COMB MAGISTERIO LTDA                1
COM DE COMB CAVALINHO LTDA F15 OSORIO        1
Name: count, Length: 42447, dtype: int64

In [52]:
df_despesas.valorDocumento.sort_values(ascending=False).head(10)

209285    209948.0
24190     178433.0
292738    164900.0
536003    150960.0
593282    149000.0
290877    148500.0
139407    140000.0
37597     140000.0
599447    130000.0
36737     130000.0
Name: valorDocumento, dtype: float64

In [53]:
df_despesas.numDocumento.value_counts().head(10)

numDocumento
s/n     10068
S/N      8784
sn       5247
SN       3553
00        998
S/Nº      888
10        656
3         654
4         638
11        624
Name: count, dtype: int64

In [54]:
df_despesas.tipoDocumento.unique()

<StringArray>
['Nota Fiscal Eletrônica',            'Nota Fiscal',         'Recibos/Outros',
    'Despesa no Exterior',    'Despesa do PARLASUL']
Length: 5, dtype: str

## **Características iniciais dos dados**

In [55]:
df_deputados.shape

(5190, 18)

In [56]:
df_deputados.info()

<class 'pandas.DataFrame'>
RangeIndex: 5190 entries, 0 to 5189
Data columns (total 18 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   id                 5190 non-null   int64
 1   uri                5190 non-null   str
 2   nomeParlamentar    5190 non-null   str
 3   siglaPartido       5190 non-null   str
 4   uriPartido         5187 non-null   str
 5   siglaUf            5190 non-null   str
 6   idLegislatura      5190 non-null   str
 7   urlFoto            5190 non-null   str
 8   email              513 non-null    str
 9   sexo               5190 non-null   str
 10  ultimaSituacao     3832 non-null   str
 11  condicaoEleitoral  5145 non-null   str
 12  nomeEleitoral      5190 non-null   str
 13  nomeCivil          5190 non-null   str
 14  dataNascimento     5155 non-null   str
 15  falecido           5190 non-null   int64
 16  udNascimento       5106 non-null   str
 17  escolaridade       4755 non-null   str
dtypes: int64(2), str(16)
memory usage: 730.0 KB

In [57]:
df_deputados.isnull().sum()

id                      0
uri                     0
nomeParlamentar         0
siglaPartido            0
uriPartido              3
siglaUf                 0
idLegislatura           0
urlFoto                 0
email                4677
sexo                    0
ultimaSituacao       1358
condicaoEleitoral      45
nomeEleitoral           0
nomeCivil               0
dataNascimento         35
falecido                0
udNascimento           84
escolaridade          435
dtype: int64

In [58]:
df_deputados.columns

Index(['id', 'uri', 'nomeParlamentar', 'siglaPartido', 'uriPartido', 'siglaUf',
       'idLegislatura', 'urlFoto', 'email', 'sexo', 'ultimaSituacao',
       'condicaoEleitoral', 'nomeEleitoral', 'nomeCivil', 'dataNascimento',
       'falecido', 'udNascimento', 'escolaridade'],
      dtype='str')

In [59]:
df_deputados.groupby(['sexo', 'siglaUf']).size()

sexo  siglaUf
F     ['AC']           13
      ['AL']            4
      ['AM']            7
      ['AP']           14
      ['BA']           16
                     ...
M     ['SC']          183
      ['SE']          100
      ['SP', 'PE']      1
      ['SP']          643
      ['TO']           50
Length: 80, dtype: int64

In [60]:
df_deputados.escolaridade.unique()

<StringArray>
[             'Secundário',                'Superior',
                       nan,          'Ensino Técnico',
           'Pós-Graduação',                'Primário',
     'Superior Incompleto',                'Mestrado',
                'Ginasial',   'Secundário Incompleto',
               'Doutorado',      'Ensino Fundamental',
            'Ensino Médio',     'Primário Incompleto',
    'Doutorado Incompleto', 'Ensino Médio Incompleto',
     'Mestrado Incompleto']
Length: 17, dtype: str

In [61]:
df_deputados.siglaPartido.value_counts()

siglaPartido
['PMDB']                               423
['PSD']                                377
['PT']                                 309
['PTB']                                265
['ARENA']                              206
                                      ...
['S.PART.', 'SOLIDARIEDADE', 'PSB']      1
['S.PART.', 'PL', 'MDB']                 1
['REPUBLICANOS', 'PV']                   1
['PDT', 'PODE']                          1
['REPUBLICANOS', 'UNIÃO']                1
Name: count, Length: 920, dtype: int64

In [62]:
df_deputados.sexo.value_counts()

sexo
M    4845
F     345
Name: count, dtype: int64

In [63]:
df_deputados.falecido.value_counts()

falecido
0    5151
1      39
Name: count, dtype: int64