## **Importação de Frameworks**

In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
pathDeputados = '/home/carlos/Documentos/ufpb/icd/IcdProject/Dados Tratados/deputados_tratado_detalhado.csv'
df = pd.read_csv(pathDeputados)

df.head()

,id,uri,nomeParlamentar,siglaPartido,uriPartido,siglaUf,idLegislatura,urlFoto,email,sexo,ultimaSituacao,condicaoEleitoral,nomeEleitoral,nomeCivil,dataNascimento,falecido,udNascimento,escolaridade
0,1500,https://dadosabertos.camara.leg.br/api/v2/depu...,MÁRIO LIMA,"['PMDB', 'PSB*']",https://dadosabertos.camara.leg.br/api/v2/part...,['BA'],"[48, 42, 47]",https://www.camara.leg.br/internet/deputado/ba...,NaN,M,Vacância,Titular,MÁRIO LIMA,MÁRIO SOARES LIMA,1935-02-19,0,BA,Secundário
1,1501,https://dadosabertos.camara.leg.br/api/v2/depu...,MAURÍCIO FRUET,"['PMDB', 'MDB*']",https://dadosabertos.camara.leg.br/api/v2/part...,['PR'],"[48, 46, 47]",https://www.camara.leg.br/internet/deputado/ba...,NaN,M,Vacância,Titular,MAURÍCIO FRUET,Maurício Roslindo Fruet,1939-08-12,0,PR,Superior
2,1502,https://dadosabertos.camara.leg.br/api/v2/depu...,OSWALDO ALMEIDA,['PL*'],https://dadosabertos.camara.leg.br/api/v2/part...,['RJ'],[48],https://www.camara.leg.br/internet/deputado/ba...,NaN,M,NaN,Titular,OSWALDO ALMEIDA,Oswaldo Barreto de Almeida,1933-10-22,0,RJ,Superior
3,1503,https://dadosabertos.camara.leg.br/api/v2/depu...,OSWALDO LIMA FILHO,"['PMDB', 'PSP', 'MDB*', 'PTB']",https://dadosabertos.camara.leg.br/api/v2/part...,['PE'],"[40, 41, 42, 43, 47, 48]",https://www.camara.leg.br/internet/deputado/ba...,NaN,M,Vacância,Efetivado,OSWALDO LIMA FILHO,Oswaldo Cavalcanti da Costa Lima Filho,1921-04-26,0,PE,Superior
4,1504,https://dadosabertos.camara.leg.br/api/v2/depu...,TITO COSTA,['PMDB'],https://dadosabertos.camara.leg.br/api/v2/part...,['SP'],[48],https://www.camara.leg.br/internet/deputado/ba...,NaN,M,NaN,Suplente,TITO COSTA,Antonio Tito Costa,1922-12-31,0,SP,Superior

### **Exploração das características iniciais dos dados**

In [5]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 5190 entries, 0 to 5189
Data columns (total 18 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   id                 5190 non-null   int64
 1   uri                5190 non-null   str
 2   nomeParlamentar    5190 non-null   str
 3   siglaPartido       5190 non-null   str
 4   uriPartido         5187 non-null   str
 5   siglaUf            5190 non-null   str
 6   idLegislatura      5190 non-null   str
 7   urlFoto            5190 non-null   str
 8   email              513 non-null    str
 9   sexo               5190 non-null   str
 10  ultimaSituacao     3832 non-null   str
 11  condicaoEleitoral  5145 non-null   str
 12  nomeEleitoral      5190 non-null   str
 13  nomeCivil          5190 non-null   str
 14  dataNascimento     5155 non-null   str
 15  falecido           5190 non-null   int64
 16  udNascimento       5106 non-null   str
 17  escolaridade       4755 non-null   str
dtypes: int64(2), str(16)
memory usage: 730.0 KB

In [6]:
df.isnull().sum()

id                      0
uri                     0
nomeParlamentar         0
siglaPartido            0
uriPartido              3
siglaUf                 0
idLegislatura           0
urlFoto                 0
email                4677
sexo                    0
ultimaSituacao       1358
condicaoEleitoral      45
nomeEleitoral           0
nomeCivil               0
dataNascimento         35
falecido                0
udNascimento           84
escolaridade          435
dtype: int64

In [7]:
df.describe()

                  id     falecido
count    5190.000000  5190.000000
mean   123536.173218     0.007514
std     49973.629149     0.086368
min      1500.000000     0.000000
25%     74533.250000     0.000000
50%    131278.500000     0.000000
75%    139364.750000     0.000000
max    235088.000000     1.000000

### **Limpeza dos dados**

In [8]:
df.columns

Index(['id', 'uri', 'nomeParlamentar', 'siglaPartido', 'uriPartido', 'siglaUf',
       'idLegislatura', 'urlFoto', 'email', 'sexo', 'ultimaSituacao',
       'condicaoEleitoral', 'nomeEleitoral', 'nomeCivil', 'dataNascimento',
       'falecido', 'udNascimento', 'escolaridade'],
      dtype='str')

In [ ]:
# Removendo colunas que não serão utilizadas na análise
df.drop(columns='email', inplace=True)

In [ ]:
# Removendo a coluna 'dataNascimento' por conter muitos valores nulos
df.drop(columns='dataNascimento', inplace=True)

In [ ]:
# Remoção da coluna 'nomeCivil' por conter os mesmo valores que a coluna 'nomeParlamentar'
df.drop(columns='nomeCivil', inplace=True)

In [ ]:
# Removendo a coluna 'nomeEleitoral' por conter os mesmo valores que a coluna 'nomeParlamentar'
df.drop(columns='nomeEleitoral', inplace=True)

### **Preechimento de valores nulos**

In [32]:
df['ultimaSituacao'] = df['ultimaSituacao'].fillna("SEM INFORMAÇÃO")

In [37]:
df['condicaoEleitoral'] = df['condicaoEleitoral'].fillna("SEM INFORMAÇÃO")

In [40]:
df['udNascimento'] = df['udNascimento'].fillna("SEM INFORMAÇÃO")

In [42]:
df['escolaridade'] = df['escolaridade'].fillna("SEM INFORMAÇÃO")

### **Padronização de colunas**

In [13]:
# PAdronização da coluna 'sexo' para facilitar a análise
df['sexo'] = df['sexo'].str.upper()

In [ ]:
# Padronização da coluna 'nomeParlamentar' para facilitar a análise
df['nomeParlamentar'] = df['nomeParlamentar'].str.upper()

In [44]:
df['ultimaSituacao'] = df['ultimaSituacao'].str.upper()

In [46]:
df['condicaoEleitoral'] = df['condicaoEleitoral'].str.upper()

In [48]:
df['escolaridade'] = df['escolaridade'].str.upper()

In [49]:
df.head()

,id,uri,nomeParlamentar,siglaPartido,uriPartido,siglaUf,idLegislatura,urlFoto,sexo,ultimaSituacao,condicaoEleitoral,falecido,udNascimento,escolaridade
0,1500,https://dadosabertos.camara.leg.br/api/v2/depu...,MÁRIO LIMA,"['PMDB', 'PSB*']",https://dadosabertos.camara.leg.br/api/v2/part...,['BA'],"[48, 42, 47]",https://www.camara.leg.br/internet/deputado/ba...,M,VACÂNCIA,TITULAR,0,BA,SECUNDÁRIO
1,1501,https://dadosabertos.camara.leg.br/api/v2/depu...,MAURÍCIO FRUET,"['PMDB', 'MDB*']",https://dadosabertos.camara.leg.br/api/v2/part...,['PR'],"[48, 46, 47]",https://www.camara.leg.br/internet/deputado/ba...,M,VACÂNCIA,TITULAR,0,PR,SUPERIOR
2,1502,https://dadosabertos.camara.leg.br/api/v2/depu...,OSWALDO ALMEIDA,['PL*'],https://dadosabertos.camara.leg.br/api/v2/part...,['RJ'],[48],https://www.camara.leg.br/internet/deputado/ba...,M,SEM INFORMAÇÃO,TITULAR,0,RJ,SUPERIOR
3,1503,https://dadosabertos.camara.leg.br/api/v2/depu...,OSWALDO LIMA FILHO,"['PMDB', 'PSP', 'MDB*', 'PTB']",https://dadosabertos.camara.leg.br/api/v2/part...,['PE'],"[40, 41, 42, 43, 47, 48]",https://www.camara.leg.br/internet/deputado/ba...,M,VACÂNCIA,EFETIVADO,0,PE,SUPERIOR
4,1504,https://dadosabertos.camara.leg.br/api/v2/depu...,TITO COSTA,['PMDB'],https://dadosabertos.camara.leg.br/api/v2/part...,['SP'],[48],https://www.camara.leg.br/internet/deputado/ba...,M,SEM INFORMAÇÃO,SUPLENTE,0,SP,SUPERIOR

In [54]:
df.condicaoEleitoral.value_counts()

condicaoEleitoral
TITULAR           3825
SUPLENTE          1105
EFETIVADO          207
SEM INFORMAÇÃO      45
NÃO ELEITO           6
ELEITO               2
Name: count, dtype: int64

In [50]:
df.isnull().sum()

id                   0
uri                  0
nomeParlamentar      0
siglaPartido         0
uriPartido           3
siglaUf              0
idLegislatura        0
urlFoto              0
sexo                 0
ultimaSituacao       0
condicaoEleitoral    0
falecido             0
udNascimento         0
escolaridade         0
dtype: int64

In [22]:
df.nomeParlamentar.value_counts()

nomeParlamentar
ROCHA LOURES        3
WILSON CUNHA        3
CARLOS ALBERTO      3
CARVALHO NETO       3
SÉRGIO CARVALHO     2
                   ..
ELMANO FÉRRER       1
VANDERLAN ALVES     1
HELOÍSA HELENA      1
CRISTIANO FURLAN    1
RIBEIRO NETO        1
Name: count, Length: 5099, dtype: int64

### **Análise Exploratória dos Dados - EDA**

### **Visualização dos Dados**